name: lb1
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+2

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  provider: ^6.1.5+1
  dartz: ^0.10.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  uuid: ^4.2.2
  shared_preferences: ^2.2.2
  dio: ^5.0.0
  json_annotation: ^4.8.1
  connectivity_plus: ^5.0.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.3
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
